### ISSUE TITLE
Support last_modified and content_length header when returning hapicFile using Pyramid

### ISSUE THREAD

**Issue by inkhey** [algoo/hapic#139]
**currently:**
Returned file using HapicFile doesn't always set content_length and last_modified header.
If we provided a filepath, that's ok, but if we provide a file object there is no such way to give content_length and last_modified information.

**expected:**
Allow to return same amount of information through header using fileobject or filepath : add content_length and last_modified header to content return with fileobject if provided.

**Comment by lebouquetin** [comment]
@inkhey the support for content_length and last_modified headers is to be supported in all frameworks, not only in pyramid.

**Comment by inkhey** [comment]
@lebouquetin this feature is not implemented at all in others framework, i created an issue to support this kind of return type for all framework : https://github.com/algoo/hapic/issues/153

**Comment by inkhey** [comment]
fixed by #140
