### ISSUE TITLE
Fix broken test on develop related to dependencies issues

### ISSUE THREAD

**Issue by inkhey** [algoo/hapic#201]
Some test are broken in upstream due to the fact dependencies are not strict and breaking changes occured on multiple package, 
to fix this we : 
1. first need to find a working combinaison of dependencies version : #202 
2. in a second time, we do need to fix support for these new library version. #203, #204, #205, #206

**Comment by inkhey** [comment]
After some search:
- apispec v3.0+ cause the issue on named schema: https://travis-ci.org/github/algoo/hapic/jobs/694176231#L1112 
- marshmallow v2 (v3 is unsupported but this is expected) get some new recent version but this doesn't seem to break anything.
- serpyco 0.18 and later break support for hapic, error is different between serpyco version, last version (1.3) get these kind of weird error :https://travis-ci.org/github/algoo/hapic/jobs/694176233#L1478 seems like serpyco has change a lot. apispec_serpyco cannot be updated to much as latest version required a recent serpyco.

**Comment by grignards** [comment]
>     * serpyco 0.18 and later break support for hapic, error is different between serpyco version, last version (1.3) get these kind of weird error :https://travis-ci.org/github/algoo/hapic/jobs/694176233#L1478 seems like serpyco has change a lot. apispec_serpyco cannot be updated to much as latest version required a recent serpyco.

The `many` parameter is now given in `load`/`dump` instead of giving it to the serializer's constructor.

**Comment by inkhey** [comment]
Tests fixed,
see  #203, #204, #205, #206 for better version support related issue
