### ISSUE TITLE
FlaskContext.get_request_parameters should cast query_parameters into dict

### ISSUE THREAD

**Issue by raphj** [algoo/hapic#212]
In Flask, `request.args` is not actually a `dict` (only a `dict`-like object) and this makes serialization fail, at least with Serpyco.

This problem is solved by casting request.args to `dict`.

The fix consists in doing this (`hapic/ext/flask/context.py`):

```python
        return RequestParameters(
            path_parameters=request.view_args,
-           query_parameters=request.args,  # TODO: Check
+           query_parameters=dict(request.args),
            body_parameters=request.get_json(),  # TODO: Check
            form_parameters=request.form,
            header_parameters=LowercaseKeysDict(
                [(k.lower(), v) for k, v in request.headers.items()]
            ),
            files_parameters=request.files,
        )
```

@buxx (cc @grignards) do you see an issue with this approach?

**Comment by raphj** [comment]
body_parameters possibly needs this too, but I haven't checked yet. This value is of whatever type returned by `itsdangerous.json.loads` which documented return type is `Any`.

https://itsdangerous.palletsprojects.com/en/2.0.x/serializer/#itsdangerous.serializer.Serializer.loads

**Comment by raphj** [comment]
I just tried, body_parameters works without casting.

**Comment by buxx** [comment]
@raphj Serpyco permit registering serializer for types. But, casting in dict is a good idea too !
