### ISSUE TITLE
List enum in generate doc

### ISSUE THREAD

**Issue by buxx** [algoo/hapic#29]
Actually schema enums are not used for doc generation. It should be. Take a look at https://github.com/marshmallow-code/apispec/pull/29 because it is apispec responsability.

**Comment by buxx** [comment]
Already managed. See 5ed744b7d1a3042960be5322bfd6b25cda0b0fd9

**Comment by lebouquetin** [comment]
@bux, which version of hapic allow this feature ?

**Comment by lebouquetin** [comment]
@buxx

**Comment by buxx** [comment]
@lebouquetin all hapic versions, it is a feature included in `apispec` since first version.

**Comment by bux** [comment]
?

**Comment by buxx** [comment]
@bux it is just a typo in @lebouquetin message ;)

By the way, happy to meet "same pseudo user"

**Comment by buxx** [comment]
@bux Funny coincidence, i am a old modder of Operation Flashpoint game, and i can see ACEmod in your repositories.

**Comment by bux** [comment]
That's really a funny coincidence. The good old days ;)
