### ISSUE TITLE
Add a feature to manage exceptions globally

### ISSUE THREAD

**Issue by lebouquetin** [algoo/hapic#43]
Currently : if I need to manage an exception for all my endpoints (for example catch `Exception` in order to generate a proper `HTTP 500`), I must add `hapic.handle_exception()` decorator on every route.

Expected : I'd like to be able to define generic exception handling which would be added automatically to every route of my APIs.

The way to do so:

Add two global methods `context.handle_exception()` and `context.handle_exceptions()` which will catch exception(s) and return properly built error responses

The implementation may be something like this:

```
# Bottle context

class BottleContext(...):
    def try_catch_decorator_builder():
        # return a decorator function
        [...]

    def handle_exception(exception_class, http_error_code):
        bottle.install(try_catch_decorator_builder)
        [...]

# Pyramid context
class PyramidContext(...):
    def handle_exception(exception_class, http_error_code):
        pyramid.add_error_view(exception_class, http_error_code)
        [...]

[...]
```

**Comment by buxx** [comment]
Development start here: https://github.com/algoo/hapic/commit/92f11b2eefc1122e3bf8234d26796f263b412332

Still require code cleaning, add comments, fix tests.
